nft_ingester/src/backfiller.rs
nft_ingester/src/main.rs
nft_ingester/src/tasks/mod.rs

* Add code to restart account and transaction tasks if they fail.
* Add code to restart backfiller if it fails.
* Add code to allow background task to recover from panics.
* Add metrics.
* I instrumented BOTH `service_account_stream` and  `service_transaction_stream` to panic and observed with this new code that it restarts both tasks.
* I instrumented the backfiller to panic and observed with this new code that it restarts the task.
* I instrumented a panic in a background task and observed that with this new code the panic is caught and the overall task manager does not crash.
* On background task I tried using various versions of `catch_unwind` but they resulted in:
```
`dyn futures_util::Future<Output = Result<(), IngesterError>> + std::marker::Send` may not be safely transferred …
```

Add code to restart tasks

---

metaplex-rpc-proxy/Cargo.lock
nft_ingester/src/tasks/mod.rs

Instrumented the `DownloadMetadata` task to fail, and observed the background task manager try 5 times then move on.

Add retries to background task manager

---

digital_asset_types/src/dapi/asset.rs

Fixes issue where API calls such as `get_assets_by_owner()` return assets in a different order each time.  The BTreeMap structure preserves key order at the expense of access time:
get | insert | remove | range | append
-- | -- | -- | -- | --
HashMap | O(1)~ | O(1)~* | O(1)~ | N/A | N/A
BTreeMap | O(log(n)) | O(log(n)) | O(log(n)) | O(log(n)) | O(n+m)
See https://doc.rust-lang.org/std/collections/index.html for more interesting info.
Computer science review: O(log(n)) means that as n increases exponentially, running time increases linearly:
n = 16: log2(16) = 4
n = 1KiB: log2(1024) = 10
n = 1 MiB: log2(1048576) = 20
n = really big: log2(1000000000000000000) = 59.794705707973
I don't think in practice this change would have any noticeable affect on our read API's performance.

Use BTreeMap in `get_asset_list_data` to preserve order

---

init.sql

Removed indeces that will fail because failed column is only created by migration.
This would prevent clean run of migrations when no database exists already.
Removing indeces for now they can be added to the migration later.

Removing indeces from missing backfiller column in init.sql

---

digital_asset_types/src/dao/generated/asset.rs
digital_asset_types/src/dao/generated/backfill_items.rs
digital_asset_types/src/dao/generated/sea_orm_active_enums.rs
migration/src/lib.rs
migration/src/m20221115_165700_add_backfiller_locked.rs
migration/src/m20221116_110500_add_backfiller_failed_and_locked_indeces.rs
nft_ingester/src/backfiller.rs

* Add migration for adding `locked` field to `backfill_items` table.
* Adding generated SeaORM code for `backfill_items` locked column.
* Adding migration to create new `backfill_items` indeces.
* Adding table lock to backfiller.
* Table lock locks `backfill_items` when getting trees to backfill, and marks these trees as locked before relinquishing the lock.
* Uses transaction mode  and `ACCESS EXCLUSIVE MODE` lock.
* Only did some basic happy-path testing so far.
* I did validate the locking worked by temporarily adding a delay and then trying to access the table from another process before the delay expired.
* Basically tested that when a new row is inserted into `backfill_items` table, the backfiller still runs, marks it as backfilled and clears the extra rows as expected, and does not …

Support multiple backfiller instances

---

nft_ingester/src/backfiller.rs

It looks like there was a bug in how the end_slot was calculated for backfilling. This lead to the backfiller always trying to fill between (curr_slot, 500_000) which would fail (no transactions fetched because usually the slot would be higher).

Fix backfilling end_slot calculation bug

---

das_api/src/api/api_impl.rs

Fixes validation of authority/owner addresses to not unwrap an Err and panic, but instead return it upstream.

Fix frontend panics

---

README.md
das_api/Cargo.lock
digital_asset_types/Cargo.lock
digital_asset_types/Cargo.toml
digital_asset_types/src/dapi/change_logs.rs
migration/Cargo.lock
nft_ingester/Cargo.lock
nft_ingester/Cargo.toml
nft_ingester/src/account_updates.rs
nft_ingester/src/backfiller.rs
nft_ingester/src/config.rs
nft_ingester/src/main.rs
nft_ingester/src/metrics.rs
nft_ingester/src/program_transformers/bubblegum/db.rs
nft_ingester/src/program_transformers/bubblegum/mod.rs
nft_ingester/src/program_transformers/mod.rs
nft_ingester/src/tasks/mod.rs

Use structured JSON logging to allow log applications (e.g. CloudWatch) to query by fields (e.g. level). Adjust log levels to reduce overall log noisiness and storage requirements.
Also switched off-chain retrieval errors to separate log and metric. This scenario is expected and polluted metrics/logs, making it harder to detect more serious errors.
Deployed e2e in Helius prod devnet and mainnet environments.

Add structured logging and reduce log noisiness

---

das_api/Cargo.lock
das_api/Cargo.toml
das_api/src/api/api_impl.rs
digital_asset_types/src/dao/scopes/asset.rs
digital_asset_types/src/dapi/assets_by_creator.rs
nft_ingester/Cargo.lock
nft_ingester/Cargo.toml

* Fixes https://github.com/metaplex-foundation/digital-asset-rpc-infrastructure/issues/51
* The SQL was querying for "creator = X OR supply > 0" instead of "creator = X AND supply >0"
* I removed the multiple creators from the query since we only ever feed a single creator to the method. Simpler code = less likely for bugs.
* Tested e2e in the Helius dev environment with mainnet data. Ensured the GetassetsByCreator returns the expected for both cases of `only_verified=true/false`.

Fix GetAssetsByCreator query

---

digital_asset_types/src/dapi/change_logs.rs

Empty proofs were being provided once we reached the 50% of the tree size.

fix(das-api): fix getAssetProof

---

das_api/src/api/api_impl.rs

Before/after strings for pagination are validated as base58 strings.
However, when we decode them into Vec<u8s> we use `as_bytes()` which uses ascii values.
Instead we need to bs58::decode them.

Fix before/after cursors by decoding base58 keys.

---

nft_ingester/Cargo.lock
nft_ingester/Cargo.toml
nft_ingester/src/config.rs
nft_ingester/src/database.rs
nft_ingester/src/error/mod.rs
nft_ingester/src/main.rs
nft_ingester/src/tasks/common/mod.rs
nft_ingester/src/tasks/mod.rs

Add configuration to the task runners, this helps address problems outlined in #50.
Adds support for a config file in addition to the environment variables. Environment variables overrides the config file values.

Configurable bgtask runner

---

digital_asset_types/src/dapi/common/asset.rs

Sometimes the assets are using non standard `url` instead of `uri` fields, and sometimes there is some problems requesting the content-types.

Fixes for asset panics

---

digital_asset_types/src/dao/scopes/asset.rs

Order by creator position so that hashing of the asset metadata generates predictable results.

Order by creator position

---

das_api/src/api/api_impl.rs
das_api/src/api/mod.rs
das_api/src/main.rs
digital_asset_types/src/dao/generated/asset.rs
digital_asset_types/src/dao/generated/asset_grouping.rs
digital_asset_types/src/dao/generated/sea_orm_active_enums.rs
digital_asset_types/src/dao/scopes/asset.rs
digital_asset_types/src/dapi/common/asset.rs
digital_asset_types/tests/common.rs
migration/src/lib.rs
migration/src/m20230720_120101_add_asset_grouping_verified.rs
migration/src/m20230720_130101_remove_asset_grouping_null_constraints.rs
migration/src/m20230724_120101_add_group_info_seq.rs
nft_ingester/src/account_updates.rs
nft_ingester/src/program_transformers/bubblegum/collection_verification.rs
nft_ingester/src/program_transformers/bubblegum/creator_verification.rs
nft_ingester/src/program_transformers/bubblegum/db.rs
nft_ingester/src/program_transformers/bubblegum/mint_v1.rs
nft_ingester/src/program_transformers/token_metadata/v1_asset.rs

* This PR is based on https://github.com/metaplex-foundation/digital-asset-rpc-infrastructure/pull/77 and https://github.com/metaplex-foundation/digital-asset-rpc-infrastructure/pull/87
* It adds support for collection verification to be indexed with out of order transactions.
* It also adds a `verified` flag so that collection verification is indexed properly.
* Verified by running a multiple sequences in order and in reverse order, and either way get same end result in `asset` and `asset_grouping` tables.
* Verified that when a collection is unverified, `getAsset` returns empty grouping.  Then after the collection is verified, `getAsset` returns the collection as a grouping.  This is to remain consistent with existing API behavior.
* See …

Fix collection verification and change to use upserts to support out of order processing

---

Api.Dockerfile
Ingest.Dockerfile
Load.Dockerfile
Migrator.Dockerfile
Proxy.Dockerfile

Some of the deps no longer build with 1.65
After updating to the Rust 1.69 image Docker builds again.

Update to Rust 1.69 docker image

---

das_api/Cargo.lock
das_api/Cargo.toml
digital_asset_types/Cargo.lock
digital_asset_types/Cargo.toml
migration/Cargo.lock
migration/Cargo.toml
nft_ingester/Cargo.lock
nft_ingester/Cargo.toml

Because solana-client 1.16 pins the tokio version to 1.14.x, we cannot easily update this RPC infra repo to Solana 1.16 yet, as the RPC infra repo uses features from newer versions of tokio.  The tokio version has since been unpinned in merged PR in the Solana repo, but I talked to Solana about this and it will not be released until 1.17.
In order to pull in creator/data hash fixes from @NicolasPennie , we need to use a newer version of Bubblegum which provides a getter method for `creator_hash` in the `LeafSchema`.  The problem is the latest Bubblegum crate has been updated to require Solana 1.16 based on requirements of Anchor 0.28 and spl-account-compression 0.2.0.
To enable the creator/data hash fixes in the RPC infra repo without updating to Solana 1.16, first a `1.14` branch was …

Use Bubblegum and Blockbuster from 1.14 branch

---

nft_ingester/src/program_transformers/token_metadata/v1_asset.rs

Collection updates were not properly indexing. If a collection does not have a seq value, the upsert condition is never met and the update is skipped. We do not need to check seq for regular NFTs since "recompression" is not live yet.
Tested locally via collection updates.

Fix collection updates for regular nfts

---

nft_ingester/src/main.rs
nft_ingester/src/metrics.rs

Based on Nick's comments it seems it was annoying to keep the version metric in every metric reported. Can be moved to only having it on the startup metric report.

Moved version metric

---

.github/workflows/test.yml
Cargo.lock
Cargo.toml
migration/src/m20230918_182123_add_raw_name_symbol.rs
tools/fetch_trees/Cargo.toml
tools/fetch_trees/src/main.rs

Updates taest workflow to build das-api components, and validate that a pr works.

Updating test workflow

---

Api.Dockerfile
Cargo.lock
Cargo.toml
Ingest.Dockerfile
Load.Dockerfile
Migrator.Dockerfile
Proxy.Dockerfile
das_api/Cargo.lock
das_api/Cargo.toml
digital_asset_types/Cargo.toml
digital_asset_types/tests/json_parsing.rs
migration/Cargo.lock
nft_ingester/Cargo.toml
nft_ingester/src/backfiller.rs
nft_ingester/src/config.rs
nft_ingester/src/program_transformers/bubblegum/collection_verification.rs
nft_ingester/src/program_transformers/bubblegum/db.rs
nft_ingester/src/program_transformers/bubblegum/mod.rs
nft_ingester/src/program_transformers/mod.rs
tools/acc_forwarder/Cargo.toml
tools/bgtask_creator/Cargo.toml
tools/fetch_trees/Cargo.toml
tools/fetch_trees/src/main.rs
tools/load_generation/Cargo.toml
tools/load_generation/src/main.rs
tools/tree-status/Cargo.toml
tools/txn_forwarder/Cargo.toml

Updates DAS API to use Solana 1.16 versions, plus the initial changes for Bubblegum Update Metadata (uses the Bubblegum Rust client that supports Update Metadata, but doesn't actually do anything with it yet).
* Change path for load generation
* Update to Solana 1.16 versions 
* Update to Solana 1.16.16 (version that does not have tokio pinned and solana-transaction-status supports Borsh 0.10.3).
* Update blockbuster to latest branch that supports Bubblegum Update Metadata instruction parsing (still a commit ID).
* Update to Borsh 0.10.3.
* Update to Plerkle Messenger 1.6.0.
* Update to Bubblegum 1.0.1-beta.2 (Rust client version that supports Update Metadata and limits to Borsh < 1.0.0).
* Update to SPL Account Compression 0.2.0.
* Update to Anchor 0.28.0.
* Update Candy Machine and …

Update to Solana 1.16 and use new Bubblegum Rust client

---

Cargo.lock
das_api/Cargo.lock
das_api/Cargo.toml
digital_asset_types/Cargo.toml
docker-compose.yaml
migration/Cargo.lock
nft_ingester/Cargo.toml
prepare-local-docker-env.sh
tools/fetch_trees/Cargo.toml

* Update `prepare-local-docker-env` script to download programs from mainnet rather than build locally from a downloaded tag.
* Update test validator image in docker compose file.
* Update blockbuster to use a beta release from the blockbuster `update-metadata-staging` branch.
* Also update to latest Bubblegum beta release which is what the blockbuster release uses.
Tested a clean build and observed it can build and run in docker, and NFTs will be periodically minted.
```
./prepare-local-docker-env.sh
docker compose up --force-recreate --build
```

Update test validator in docker and blockbuster version

---

nft_ingester/src/program_transformers/bubblegum/mint_v1.rs
nft_ingester/src/program_transformers/bubblegum/mod.rs

Bubblegum allows for empty URIs. When this happens, the indexer will reject the transaction leading to a missing NFT in the API response. To fix, we allow the record to index and skip the off-chain indexing update.
Running in Helius fork in prod.
Keep in mind that we are 1.14 for ingester at the moment, so I have not perfectly reproduced these changes on the Metaplex version. The changes are simple though and should be fine.

fix: allow no metadata for cnft mints

---

nft_ingester/src/program_transformers/bubblegum/mint_v1.rs

In a previous PR we allow URI to be empty and not create a background task, but we need to remove this early return otherwise it will still return early.
(It is already removed in the helius-labs version from which the previous PR's change was upstreamed)

Remove early return if uri is empty

---

nft_ingester/src/config.rs
nft_ingester/src/database.rs
nft_ingester/src/main.rs

This makes the worker configuration more dynamic, by letting you specify custom streams in the config file. It also removes an unnecessary dependency between plerkle_messenger and the ingester in pulling the names of the stream from plerkle messenger.
The default behaviour of the ingester stays the same, creating 2 workers for TXN and 2 workers for ACC streams by default.

Configurable account streams

---

nft_ingester/src/program_transformers/token/mod.rs
nft_ingester/src/program_transformers/token_metadata/v1_asset.rs

Issue
Many SPL tokens have an associated metadata account but lack a defined token_standard. The current ingester version incorrectly categorizes such SPL tokens as having an ownership_type due to this undefined token_standard. The token_account_update handler, responsible for account changes, references the associated asset. If the token_account's held amount is t.amount > 0 AND asset.ownership_type == OwnerType::Single, the asset's owner field updates to the token account's owner. This leads to SPL token exchanges triggering frequent ownership updates on the asset, resulting in excessive single-row updates in the database. These updates cause locks that severely hamper the database's message processing capabilities, leading to queue backups.
```
2023-11-28 10:18:36.994 UTC [3417847] …
```

Stop Token Spam on Asset Table

---

das_api/src/error.rs
digital_asset_types/src/dao/mod.rs
digital_asset_types/src/rpc/filter.rs
nft_ingester/src/program_transformers/token/mod.rs
nft_ingester/src/program_transformers/token_metadata/mod.rs
nft_ingester/src/program_transformers/token_metadata/v1_asset.rs

* Indexing improvements for regular NFTs.
* Fix parsing for ownership types based on token standard. 
*  If a token standard is unknown, but supply=1, then mark it as an NFT. If supply > 1, mark it as fungible.
* In v1_asset, retry the fetch for a mint/token account since all accounts can arrive at once during an NFT mint.
* Query only well-formed tokens by default w/ search assets (like getAssetsByOwner). Only query NFTs, since only NFTs are supported at the moment. These changes avoid inconsistencies in the responses that confused our customers.
* TLDR: Your queries only include well-defined NFTs unless you configure flags like supply/owner_type yourself (no one really does).
These changes are running in Helius production, but I also ran the code locally and spot checked against regular …

Improvements for NFT indexing and query consistency

---

nft_ingester/src/program_transformers/bubblegum/update_metadata.rs

- Empty URI's are allowed. This caused the transaction indexing to fail.
- At the time of writing, the only impacted asset is `5xg1NhPgYajc3LYzv5T5RT9vfxVP3s2uyT9zTb9azu1f`. I recommend other providers scan their logs and verify no other assets have been impacted since we fixed it.
- Re-indexed the record in Helius' production environment

Fix cNFT update metadata indexing

---

Cargo.lock
Cargo.toml
core/Cargo.toml
core/src/db.rs
core/src/lib.rs
core/src/metrics.rs
migration/src/lib.rs
migration/src/m20240124_173104_add_tree_seq_index_to_cl_audits_v2.rs
ops/Cargo.toml
ops/src/bubblegum/README.md
ops/src/bubblegum/backfiller.rs
ops/src/bubblegum/cmd.rs
ops/src/bubblegum/mod.rs
ops/src/bubblegum/queue.rs
ops/src/bubblegum/rpc.rs
ops/src/bubblegum/tree.rs
ops/src/main.rs

resolves https://github.com/metaplex-foundation/digital-asset-rpc-infrastructure/issues/150
Implement a rapid, efficient, and reliable method for backfilling any missing updates to bubblegum trees.
- Introduce an ops crate that consolidates various operational tools utilized by DAS operators.
- Implement a bubblegum backfill command. This command detects absent trees and their sequences within the index by referencing cl_audits_v2. It then requests missing transactions for a tree using getSignaturesForAddress to requeue any missed transactions. For usage details and methodology, refer to the bubblegum module's [README](https://github.com/metaplex-foundation/digital-asset-rpc-infrastructure/blob/78479394b8465d9353515513bdc9a986b6079316/ops/src/bubblegum/README.md).
At Triton, the backfill …

[Feat] Ops cli with tree backfiller

---

Api.Dockerfile
Cargo.lock
Cargo.toml
Ingest.Dockerfile
Load.Dockerfile
Migrator.Dockerfile
Proxy.Dockerfile
nft_ingester/src/backfiller.rs

Fix docker buiild by adding blockbuster.
Update stretto version/usage since wg version 0.3 was yanked which broke stretto 0.7.2

Fix docker build and update stretto

---

integration_tests/tests/integration_tests/common.rs
nft_ingester/src/account_updates.rs
nft_ingester/src/main.rs
nft_ingester/src/transaction_notifications.rs
program_transformers/src/bubblegum/burn.rs
program_transformers/src/bubblegum/cancel_redeem.rs
program_transformers/src/bubblegum/collection_verification.rs
program_transformers/src/bubblegum/creator_verification.rs
program_transformers/src/bubblegum/db.rs
program_transformers/src/bubblegum/delegate.rs
program_transformers/src/bubblegum/mint_v1.rs
program_transformers/src/bubblegum/mod.rs
program_transformers/src/bubblegum/redeem.rs
program_transformers/src/bubblegum/transfer.rs
program_transformers/src/bubblegum/update_metadata.rs
program_transformers/src/lib.rs

Currently the writing of cl_audits_v2 is managed by a config option. However, getAssetSignatures requires the cl_audits_v2 table in order to return signatures history for a bubblegum asset.
As of today the cl_audits_v2 table is 170GB when there are 330GB of cl_items.
- Always write cl_audit_v2 records by dropping the cl_audits config option.

Always Write CL_AUDITS_V2

---

nft_ingester/src/config.rs
nft_ingester/src/main.rs

This PR makes parsing rollups as an optional feature which could be enabled/disabled through the config.
Rollups data may take lot of space and not every DAS API operator is ready to store it.
Was added a new config parameter and check of this paramenter in main func.

Make rollup processing feature optional

---

blockbuster/src/programs/token_extensions/extension.rs
blockbuster/src/programs/token_extensions/mod.rs

add remaining extensions to token-2022 handler

---

Cargo.lock
digital_asset_types/src/dapi/change_logs.rs
digital_asset_types/tests/common.rs
nft_ingester/src/backfiller.rs
nft_ingester/src/plerkle.rs
nft_ingester/src/tasks/mod.rs
ops/src/bubblegum/tree.rs
program_transformers/src/bubblegum/db.rs
rust-toolchain.toml

grpc-ingest branch will use rust-1.79 and this will cause clippy warnings so making this pr to fix those clippy warnings 
- Upgrade rust toolchain to 1.79
- Resolve clippy warnings

fix : cargo clippy for rust-1.79

---

Api.Dockerfile
Builder.Dockerfile
Cargo.lock
Ingest.Dockerfile
Load.Dockerfile
Migrator.Dockerfile
Proxy.Dockerfile
rust-toolchain.toml

I did also try using the lockfile and passing `--locked` to the docker build, but this causes an issue with `cargo install wasm-pack` which still needs the latest Rust version, so just opted to update Rust version.
Updating to latest Rust caused me to need to update time crate as well.
Local build works and `docker compose up --force-recreate --build` works.

Update rust version in toolchain file and docker files

---

integration_tests/tests/integration_tests/snapshots/integration_tests__token_accounts_tests__get_token_accounts_by_owner.snap

I think since we have this code:
```
let token_accounts = paginate(
pagination,
limit,
token_accounts::Entity::find().filter(condition),
Order::Asc,
token_accounts::Column::Pubkey,
)
.all(conn)
.await?;
```
It is expected to order by ascending which means numbers come first before letters in Postgres.

Change ordering in get_token_accounts_by_owner integ test result
