metaplex-foundation/digital-asset-rpc-infrastructure

README.md

Updated config variable to be accurate.

Updated config variable documentation

---

.github/workflows/test.yml
das_api/Cargo.lock
digital_asset_types/Cargo.toml
nft_ingester/Cargo.lock
nft_ingester/Cargo.toml
nft_ingester/src/backfiller.rs
nft_ingester/src/program_transformers/common/mod.rs
nft_ingester/src/program_transformers/mod.rs

Thank you for taking the time to make an enhancement or bug fix to the digital asset validator rpc repo.
To ensure a quality PR experience this call may be recorded. Just Kidding, but we do expect a few things.
1. The Name of the PR will show up in the changelog so make it a good one, we will rename PRs or reject based on the name.
2. Please make the PR as small as possible to achieve the bugfix or feature. Big prs often are scary and hard to review.
3. Be kind to your reviewers 🤓
4. Add a good description, so we can see what the PR is all about without investing the time in the code review. We will often review code at a certain time in the day and having a list if important prs to review helps us move that along.

upgrades blockbuster and fixes basic types

---

das_api/src/api.rs
das_api/src/api_impl.rs
das_api/src/error.rs
das_api/src/rpc-tests.http
digital_asset_types/src/dapi/mod.rs
digital_asset_types/src/dapi/search_assets.rs

* Ported over from reference implementation.
* Modified `search_assets` to use `get_asset_list_data` to get the `built_assets list`.
* Didn't deep dive the actual creating of `get_asset_list_data` since it is similar code to `assets_by_creator` etc.
* Fixed other minor compatibility issues, minor clean up of code.
* Add pubkey-based conditions to search_assets.
* Add enum-based conditions to search_assets
* Add DateTimeWithTimeZone-based conditions to search_assets.
```
POST http://localhost:9090 HTTP/1.1
content-type: application/json
{
"jsonrpc": "2.0",
"method": "search_assets",
"params": [
{
"supply": 1,
"compresssed": false,
"burnt": false
},
"created",
50,
1,
"",
""
],
"id": 0
}
```
```
HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
content-length: 39635
date: Wed, 02 …
```

add `search_assets`

---

migration/src/m20230310_162227_add_indexes_to_bg.rs

Fix migration

---

nft_ingester/src/error/mod.rs
nft_ingester/src/tasks/common/mod.rs
nft_ingester/src/tasks/mod.rs

Handles and logs RPC errors separately.

Handle HTTP errors

---

digital_asset_types/src/dao/full_asset.rs
digital_asset_types/src/dao/mod.rs
digital_asset_types/src/dapi/common/asset.rs
nft_ingester/src/account_updates.rs
nft_ingester/src/backfiller.rs
nft_ingester/src/database.rs
nft_ingester/src/program_transformers/bubblegum/decompress.rs
nft_ingester/src/program_transformers/mod.rs
nft_ingester/src/program_transformers/token/mod.rs
nft_ingester/src/transaction_notifications.rs

Removing a bunch of unused imports to reduce clippy's warnings a bit.

Fixing unused imports

---

digital_asset_types/src/dapi/common/asset.rs
digital_asset_types/src/rpc/asset.rs

Fix edition nonce

---

das_api/src/api/api_impl.rs
das_api/src/api/mod.rs
digital_asset_types/src/dao/mod.rs
digital_asset_types/src/dao/scopes/asset.rs

Support optional filtering by `jsonUri` in `searchAssets` API method

feat(das-api): support searching assets by `jsonUri` parameter

---

das_api/src/api/api_impl.rs
das_api/src/api/mod.rs

This closes #70 .
Adds a few frontend fixes from helius-labs/digital-asset-rpc-infrastructure.

Frontend fixes - reject unknown fields and handle page 0

---

das_api/Cargo.lock
digital_asset_types/Cargo.lock
metaplex-rpc-proxy/Cargo.lock
migration/Cargo.lock
nft_ingester/Cargo.lock

Fixes CI build using latest rustc.

Updating proc-macro2 and log to latest patch releases

---

das_api/src/error.rs

Minor fix for error conversions.

Change error type

---

das_api/src/api/api_impl.rs
das_api/src/api/mod.rs

upstreaming pr from helius labs to ensure compatible apis: 
https://github.com/helius-labs/digital-asset-rpc-infrastructure/pull/73

fix: make delegate string (#73)

---

nft_ingester/src/backfiller.rs
nft_ingester/src/config.rs

Adds a configuration param that allows limiting which trees the backfiller tries to backfill.

Added config param for backfilling specific trees

---

digital_asset_types/src/dao/generated/asset_data.rs
digital_asset_types/tests/common.rs
digital_asset_types/tests/json_parsing.rs
migration/src/lib.rs
migration/src/m20230918_182123_add_raw_name_symbol.rs
nft_ingester/src/program_transformers/bubblegum/mint_v1.rs
nft_ingester/src/program_transformers/token_metadata/v1_asset.rs

Adds raw_name and raw_symbol for each NFT 
Backport of https://github.com/helius-labs/digital-asset-rpc-infrastructure/pull/54/files#diff-69b5957478ab6dbb79664bb9263e183e36d1828716f86c4732929474ef91819bL74.

Add raw_name and raw_symbol

---

Cargo.lock
migration/src/m20230918_182123_add_raw_name_symbol.rs

Fix raw name build

---

Cargo.lock
Cargo.toml
tools/fetch_trees/Cargo.toml
tools/fetch_trees/src/main.rs

Fetches a list of trees from an RPC endpoint.

Added fetch trees tool

---

nft_ingester/src/config.rs
nft_ingester/src/main.rs

port of https://github.com/rpcpool/digital-asset-rpc-infrastructure/pull/105

nft ingester: add backfill workers count to config

---

Api.Dockerfile
Ingest.Dockerfile
Load.Dockerfile
Migrator.Dockerfile
Proxy.Dockerfile

* Update Rust version
* Add core, integration_tests, and ops directories from recent DAS updates
* `docker compose up --force-recreate --build` works.

Update Rust version and missing dirs in docker build

---

digital_asset_types/src/dao/extensions/asset_grouping.rs
program_transformers/src/mpl_core_program/v1_asset.rs

resolves https://github.com/metaplex-foundation/digital-asset-rpc-infrastructure/pull/185

MPL Core Authority Syncing for Collections

---

LICENSE

_@danenbm UPDATE:  I am currently working on adding all contributors who need to approve the license change to this PR.  Some are still in the process of being invited as a collaborator so that I can list them as a reviewer.  We need to wait to merge this until all needed contributors approve, or we have offline sign off._
This repo needs a license, and the more contributors we have to the repo the greater urgency to actually define that license. Each contributor will have to agree/sign off on the license we pick.

Proposal for AGPL licensing

---

das_api/src/api/api_impl.rs

Implemented PubKey validation for group_key in getAssetByGroup

---

.github/workflows/build-api.yml
.github/workflows/test.yml

bump to v4
1. action/checkout 
2. actions/cache
3. actions/upload-artifacts

update few actions workflows to v4

---

das_api/src/api/api_impl.rs
das_api/src/api/mod.rs
digital_asset_types/src/dao/mod.rs
digital_asset_types/src/dao/scopes/asset.rs
digital_asset_types/src/dapi/common/asset.rs

revert searchAssets condition order and cover all cases for nft filter

---

digital_asset_types/src/dao/scopes/asset.rs
digital_asset_types/src/dapi/get_asset.rs

Add asset supply checks and return meaningful error message for getAsset method
